
version: '3'
services: 
    nginx:
        build: nginx/.
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./php/:/var/www/test/
        links:
            - fpm
    fpm:
        build: php/.
        ports:
            - "9000:9000"
        volumes:
            - ./php/:/var/www/test/
        links: 
            - mydb

    mydb:
        image: shubhampwr885/project_student_db
        ports: 
            - 3306
        environment:
            - "MYSQL_ROOT_PASSWORD=wifi123#"
     